# Generated by Django 4.1.3 on 2022-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('courses_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_description', models.CharField(max_length=200)),
                ('courses_date', models.DateField()),
                ('courses_age', models.IntegerField()),
                ('courses_requirements', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('submissions_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissions_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('users_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_pass', models.CharField(max_length=200)),
                ('users_region', models.CharField(max_length=45)),
                ('users_surname', models.CharField(max_length=20)),
                ('users_name', models.CharField(max_length=20)),
                ('users_patronymic', models.CharField(max_length=20)),
                ('users_phone', models.CharField(max_length=20)),
                ('users_email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='users_documents',
            fields=[
                ('users_documents_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_documents_passport', models.IntegerField()),
                ('users_documents_education', models.CharField(max_length=100)),
                ('users_documents_snils', models.CharField(max_length=20)),
            ],
        ),
    ]
