# Generated by Django 4.1.3 on 2022-11-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='courses_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='submissions_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='users_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users_documents',
            old_name='users_documents_id',
            new_name='id',
        ),
    ]
