# Generated by Django 4.1.3 on 2022-12-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_courses_id_courses_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courses_age',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='courses_date',
        ),
        migrations.AddField(
            model_name='courses',
            name='courses_name',
            field=models.CharField(default='default name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='courses_urls',
            field=models.CharField(default='default courses_urls', max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='users_login',
            field=models.CharField(default='default users_login', max_length=30),
        ),
    ]
