# Generated by Django 4.1.3 on 2022-12-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_courses_courses_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courses_urls',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_login',
            field=models.CharField(max_length=30),
        ),
    ]
