# Generated by Django 4.1.3 on 2022-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_courses_courses_urls_alter_users_users_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courses_description',
            field=models.CharField(max_length=200, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courses_name',
            field=models.CharField(max_length=20, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courses_requirements',
            field=models.CharField(max_length=20, verbose_name='Требования к курсу'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courses_urls',
            field=models.CharField(max_length=30, null=True, verbose_name='Ссылка на курс'),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_email',
            field=models.EmailField(max_length=30, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_login',
            field=models.CharField(max_length=30, verbose_name='Логин пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_pass',
            field=models.CharField(max_length=200, verbose_name='Пароль пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_patronymic',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_region',
            field=models.CharField(max_length=45, verbose_name='Регион проживания пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_surname',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='users_documents',
            name='users_documents_education',
            field=models.CharField(max_length=100, verbose_name='Документ об образовании пользователя'),
        ),
        migrations.AlterField(
            model_name='users_documents',
            name='users_documents_passport',
            field=models.CharField(max_length=10, verbose_name='Паспорт пользователя'),
        ),
        migrations.AlterField(
            model_name='users_documents',
            name='users_documents_snils',
            field=models.CharField(max_length=20, null=True, verbose_name='Снилс пользователя'),
        ),
    ]
