# Generated by Django 4.1.3 on 2022-12-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_courses_courses_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['courses_name'], 'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='users_documents',
            options={'verbose_name': 'Документы пользователей', 'verbose_name_plural': 'Документы пользователей'},
        ),
    ]
