# Generated by Django 4.1.3 on 2022-12-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_users_documents_users_documents_passport_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courses_published',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
